# PTU (Power Transfer Unit) Assembly — Mate Constraint Version
# Demonstrates: declarative mate constraints (coaxial, coincident, distance)
# Same parts as ptu_assembly.toml, but using mates instead of manual coordinates.

name = "ptu_assembly_mates"

# ── Export ───────────────────────────────────────────────────
[export]
formats = ["step", "stl"]
directory = "./output"


# ═════════════════════════════════════════════════════════════
# PART DEFINITIONS (identical to ptu_assembly.toml)
# ═════════════════════════════════════════════════════════════

# ── 1. Housing (revolution body with bore) ──────────────────
[[parts]]
id = "housing"
final = "body"

  [[parts.shapes]]
  id = "outer"
  type = "revolution"
  angle = 360
  axis = [0, 0, 1]
  axis_point = [0, 0, 0]
  plane = "xz"
  profile_start = [0, 0]

    [[parts.shapes.profile]]
    type = "line"
    to = [40, 0]

    [[parts.shapes.profile]]
    type = "line"
    to = [40, 10]

    [[parts.shapes.profile]]
    type = "line"
    to = [50, 10]

    [[parts.shapes.profile]]
    type = "line"
    to = [50, 15]

    [[parts.shapes.profile]]
    type = "line"
    to = [40, 15]

    [[parts.shapes.profile]]
    type = "line"
    to = [40, 60]

    [[parts.shapes.profile]]
    type = "arc"
    to = [35, 65]
    center = [35, 60]
    clockwise = false

    [[parts.shapes.profile]]
    type = "line"
    to = [0, 65]

  [[parts.shapes]]
  id = "bore"
  type = "revolution"
  angle = 360
  axis = [0, 0, 1]
  plane = "xz"
  profile_start = [0, 3]

    [[parts.shapes.profile]]
    type = "line"
    to = [33, 3]

    [[parts.shapes.profile]]
    type = "line"
    to = [33, 62]

    [[parts.shapes.profile]]
    type = "line"
    to = [0, 62]

  [[parts.shapes]]
  id = "bolt_hole"
  type = "cylinder"
  radius = 4
  height = 20
  position = [45, 0, -5]

  [[parts.operations]]
  op = "cut"
  base = "outer"
  tool = "bore"
  result = "body"

  [[parts.operations]]
  op = "circular_pattern"
  target = "bolt_hole"
  axis = [0, 0, 1]
  center = [0, 0, 0]
  count = 6
  angle = 360
  include_original = true
  result = "bolt_holes"

  [[parts.operations]]
  op = "cut"
  base = "body"
  tool = "bolt_holes"
  result = "body"


# ── 2. Input Shaft ──────────────────────────────────────────
[[parts]]
id = "input_shaft"
final = "shaft"

  [[parts.shapes]]
  id = "shaft_body"
  type = "library/stepped_shaft"
  bore_d = 0

    [[parts.shapes.segments]]
    diameter = 20
    length = 15

    [[parts.shapes.segments]]
    diameter = 24
    length = 30

    [[parts.shapes.segments]]
    diameter = 20
    length = 15

  [[parts.shapes]]
  id = "keyway"
  type = "extrusion"
  direction = [0, 0, 25]
  plane = "xy"
  position = [0, 0, 17]
  profile_start = [-2, 9]

    [[parts.shapes.profile]]
    type = "line"
    to = [2, 9]

    [[parts.shapes.profile]]
    type = "line"
    to = [2, 13]

    [[parts.shapes.profile]]
    type = "line"
    to = [-2, 13]

  [[parts.operations]]
  op = "cut"
  base = "shaft_body"
  tool = "keyway"
  result = "shaft"


# ── 3. Drive Gear ───────────────────────────────────────────
[[parts]]
id = "drive_gear"

  [[parts.shapes]]
  id = "gear"
  type = "library/spur_gear"
  module = 2
  teeth = 20
  width = 10
  bore_d = 24
  pressure_angle = 20


# ── 4. Front Bearing ────────────────────────────────────────
[[parts]]
id = "bearing_front"

  [[parts.shapes]]
  id = "brg"
  type = "library/ball_bearing"
  inner_d = 20
  outer_d = 42
  width = 12
  num_balls = 8


# ── 5. Rear Bearing ─────────────────────────────────────────
[[parts]]
id = "bearing_rear"

  [[parts.shapes]]
  id = "brg"
  type = "library/ball_bearing"
  inner_d = 20
  outer_d = 42
  width = 12
  num_balls = 8


# ═════════════════════════════════════════════════════════════
# ASSEMBLY — Mate Constraints
# ═════════════════════════════════════════════════════════════

[assembly]

  # Housing is the anchor
  [[assembly.parts]]
  ref = "housing"
  position = [0, 0, 0]

  # Shaft placed by coaxial + distance to housing
  [[assembly.parts]]
  ref = "input_shaft"

  # Gear placed by coaxial to shaft
  [[assembly.parts]]
  ref = "drive_gear"

  # Bearings placed by coaxial to shaft + distance from housing faces
  [[assembly.parts]]
  ref = "bearing_front"

  [[assembly.parts]]
  ref = "bearing_rear"

  # ── Mates ─────────────────────────────────────────────────

  # Shaft coaxial with housing bore
  [[assembly.mates]]
  type = "coaxial"
  part1 = "housing"
  face1 = "cyl:z:min"
  part2 = "input_shaft"
  face2 = "cyl:z"

  # Shaft bottom face sits 3mm above housing bottom
  [[assembly.mates]]
  type = "distance"
  part1 = "housing"
  face1 = "plane:+z:min"
  part2 = "input_shaft"
  face2 = "plane:-z:min"
  value = 3.0

  # Drive gear coaxial with shaft
  [[assembly.mates]]
  type = "coaxial"
  part1 = "input_shaft"
  face1 = "cyl:z"
  part2 = "drive_gear"
  face2 = "cyl:z:min"

  # Drive gear positioned 20mm from housing base
  [[assembly.mates]]
  type = "distance"
  part1 = "housing"
  face1 = "plane:+z:min"
  part2 = "drive_gear"
  face2 = "plane:-z:min"
  value = 20.0

  # Front bearing coaxial with shaft
  [[assembly.mates]]
  type = "coaxial"
  part1 = "input_shaft"
  face1 = "cyl:z"
  part2 = "bearing_front"
  face2 = "cyl:z:min"

  # Front bearing 5mm from housing base
  [[assembly.mates]]
  type = "distance"
  part1 = "housing"
  face1 = "plane:+z:min"
  part2 = "bearing_front"
  face2 = "plane:-z:min"
  value = 5.0

  # Rear bearing coaxial with shaft
  [[assembly.mates]]
  type = "coaxial"
  part1 = "input_shaft"
  face1 = "cyl:z"
  part2 = "bearing_rear"
  face2 = "cyl:z:min"

  # Rear bearing 50mm from housing base
  [[assembly.mates]]
  type = "distance"
  part1 = "housing"
  face1 = "plane:+z:min"
  part2 = "bearing_rear"
  face2 = "plane:-z:min"
  value = 50.0
